language: cpp

os: linux

compiler:
        - clang
        - gcc

branches:
    only:
        - master

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - g++-5
      - g++-6

matrix:
  include:
    - os: linux
      sudo: false
      env: GCC_VER="4.9"
      compiler: gcc
      #    - os: linux
      #sudo: false
      #env: GCC_VER="6" CMAKE_OPTIONS="-D DYNLOAD_ENABLED:BOOL=FALSE -D MULTITHREAD_SUPPORT_ENABLED:BOOL=FALSE -D USE_STD_MAKE_SHARED:BOOL=TRUE" BUILD_ONLY=1
      #compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="5"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="6"
      compiler: gcc
    - os: linux
      sudo false
      compiler: clang

before_install:
  - if [ "${GCC_VER}" != "" ]; then export CXX="g++-$GCC_VER" CC="gcc-$GCC_VER" GCOV="gcov-$GCC_VER" ; fi
  - pip install --user cpp-coveralls
  - sudo apt-get install -y libgsl-dev

script:
        - mkdir build;
          make all
