language: cpp

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
        - gcc-4.9
        - gcc-5.0
        - gcc-6.0
        - gcc-7.0
        - gcc-8.0

matrix:
  include:
    - os: linux
      sudo: false
      env: GCC_VER="4.9"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="5"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="6"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="7"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="8"
      compiler: gcc

before_install:
  - if [ "${GCC_VER}" != "" ]; then export CXX="g++-$GCC_VER" CC="gcc-$GCC_VER" GCOV="gcov-$GCC_VER" ; fi
  - pip install --user cpp-coveralls
  - sudo apt-get install -y libgsl0-dev libopenblas-dev

script:
    - mkdir build
    - make travis
